In [20]:
%matplotlib inline

In [21]:
path = "/home/ubuntu/nbs/data/dogs-vs-cats-redux-kernels-edition/sample/"

In [22]:
from __future__ import division, print_function

import os, json
from glob import glob
import numpy as np
np.set_printoptions(precision=4, linewidth=100)
from matplotlib import pyplot as plt

In [23]:
% cd "/home/ubuntu/nbs"
import utils; reload(utils)
from utils import plots

/home/ubuntu/nbs


Using gpu device 0: Tesla K80 (CNMeM is disabled, cuDNN 5103)
/home/ubuntu/anaconda2/lib/python2.7/site-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)
Using Theano backend.


In [24]:
batch_size = 64

In [25]:
import vgg16; reload(vgg16)
from vgg16 import Vgg16

In [7]:
% cd "/home/ubuntu/nbs/data/dogs-vs-cats-redux-kernels-edition/train"

/home/ubuntu/nbs/data/dogs-vs-cats-redux-kernels-edition/train


In [10]:
# create sample set for train cats 
from shutil import copyfile
g = glob('cat*.jpg')
shut = np.random.permutation(g)
for i in range(200): copyfile(shut[i], '../sample/train/cats/' + shut[i])



In [9]:
# create sample set for train dogs
from shutil import copyfile
g = glob('dog*.jpg')
shut = np.random.permutation(g)
for i in range(200): copyfile(shut[i], '../sample/train/dogs/' + shut[i])

In [ ]:
# create sample set for valid cats 
from shutil import copyfile
g = glob('cat*.jpg')
shut = np.random.permutation(g)
for i in range(20): copyfile(shut[i], '../sample/valid/cats/' + shut[i])

In [ ]:
# create sample set for valid dogs 
from shutil import copyfile
g = glob('dog*.jpg')
shut = np.random.permutation(g)
for i in range(20): copyfile(shut[i], '../sample/valid/dogs/' + shut[i])

In [26]:
% cd "/home/ubuntu/nbs"

vgg = Vgg16()
batches = vgg.get_batches(path + 'train', batch_size=batch_size)
val_batches = vgg.get_batches(path + 'valid', batch_size=batch_size*2)
vgg.finetune(batches)
vgg.fit(batches, val_batches, nb_epoch=1)

/home/ubuntu/nbs
Found 400 images belonging to 2 classes.
Found 40 images belonging to 2 classes.
Epoch 1/1
400/400 [==============================] - 11s - loss: 1.2241 - acc: 0.7000 - val_loss: 0.8260 - val_acc: 0.7500


In [27]:
imgs, labels = next(batches)

In [28]:
imgs

array([[[[ 135.,  135.,  134., ...,  162.,  175.,  179.],
         [ 136.,  140.,  143., ...,  164.,  175.,  178.],
         [ 138.,  140.,  140., ...,  164.,  175.,  165.],
         ..., 
         [  83.,   81.,   57., ...,  130.,  130.,  130.],
         [  29.,   24.,   13., ...,  130.,  130.,  130.],
         [  24.,   20.,    7., ...,  130.,  130.,  130.]],

        [[ 118.,  118.,  117., ...,  145.,  158.,  165.],
         [ 119.,  123.,  126., ...,  147.,  158.,  164.],
         [ 121.,  123.,  123., ...,  147.,  158.,  151.],
         ..., 
         [ 101.,   99.,   71., ...,  110.,  110.,  110.],
         [  47.,   40.,   27., ...,  110.,  110.,  110.],
         [  37.,   33.,   19., ...,  110.,  110.,  110.]],

        [[ 111.,  111.,  110., ...,  138.,  151.,  178.],
         [ 112.,  116.,  119., ...,  140.,  151.,  177.],
         [ 114.,  116.,  116., ...,  140.,  151.,  164.],
         ..., 
         [  85.,   83.,   58., ...,  112.,  112.,  112.],
         [  31.,   27.,

In [16]:
vgg.predict(imgs, True)

(array([ 0.7081,  1.    ,  0.9999,  0.9999,  0.9985,  1.    ,  0.775 ,  0.9999,  0.9692,  0.9981,
         0.9994,  0.9141,  0.9975,  0.9992,  0.996 ,  1.    ,  0.9978,  0.9983,  0.6976,  0.9986,
         0.9961,  0.9808,  0.9997,  0.9991,  1.    ,  0.9989,  1.    ,  0.9827,  0.9987,  0.9998,
         0.7334,  0.7989], dtype=float32),
 array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
        1]),
 [u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'tench',
  u'tench',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'tench',
  u'tench',
  u'tench',
  u'goldfish',
  u'goldfish',
  u'tench',
  u'goldfish',
  u'goldfish'])

In [18]:
len(imgs)

32

In [29]:
vgg.classes[:4]

[u'tench', u'goldfish', u'great_white_shark', u'tiger_shark']

In [30]:
imgs[0]

array([[[ 135.,  135.,  134., ...,  162.,  175.,  179.],
        [ 136.,  140.,  143., ...,  164.,  175.,  178.],
        [ 138.,  140.,  140., ...,  164.,  175.,  165.],
        ..., 
        [  83.,   81.,   57., ...,  130.,  130.,  130.],
        [  29.,   24.,   13., ...,  130.,  130.,  130.],
        [  24.,   20.,    7., ...,  130.,  130.,  130.]],

       [[ 118.,  118.,  117., ...,  145.,  158.,  165.],
        [ 119.,  123.,  126., ...,  147.,  158.,  164.],
        [ 121.,  123.,  123., ...,  147.,  158.,  151.],
        ..., 
        [ 101.,   99.,   71., ...,  110.,  110.,  110.],
        [  47.,   40.,   27., ...,  110.,  110.,  110.],
        [  37.,   33.,   19., ...,  110.,  110.,  110.]],

       [[ 111.,  111.,  110., ...,  138.,  151.,  178.],
        [ 112.,  116.,  119., ...,  140.,  151.,  177.],
        [ 114.,  116.,  116., ...,  140.,  151.,  164.],
        ..., 
        [  85.,   83.,   58., ...,  112.,  112.,  112.],
        [  31.,   27.,   14., ...,  112., 